Repository igortereshchenko/datascience, pull requests merged in 2019-12, with the labels that each got.

#100 validator
  budzinskiyeo/__init__.py
  budzinskiyeo/dataset_insert_manual.py
  budzinskiyeo/dataset_structure.py
  budzinskiyeo/description.txt
  budzinskiyeo/recursion.py
  budzinskiyeo/validator/__init__.py
  budzinskiyeo/validator/lib.py
  budzinskiyeo/validator/test.py
Labels: shoe

#96 dataset_structure
  snitsarenkoas/__init__.py
  snitsarenkoas/dataset_structure.py
  snitsarenkoas/description.txt
  snitsarenkoas/validator/__init__.py
  snitsarenkoas/validator/lib.py
  snitsarenkoas/validator/test.py
Labels: shoe

#85 validator
  NedilkoDV/__init__.py
  NedilkoDV/dataset_inset_manual.py
  NedilkoDV/dataset_structure.py
  NedilkoDV/description.txt
  NedilkoDV/recursion.py
  NedilkoDV/validator/__init__.py
  NedilkoDV/validator/lib.py
  NedilkoDV/validator/test.py
Labels: shoe

#94 validator
  stefanyshynni/__init__.py
  stefanyshynni/dataset_insert_manual.py
  stefanyshynni/dataset_structure.py
  stefanyshynni/description.txt
  stefanyshynni/recursion.py
  stefanyshynni/validator/__init__.py
  stefanyshynni/validator/lib.py
  stefanyshynni/validator/test.py
Labels: shoe

#89 validator
  miroshnyk_a_v/__init__.py
  miroshnyk_a_v/dataset_insert_manual.py
  miroshnyk_a_v/dataset_structure.py
  miroshnyk_a_v/description.txt
  miroshnyk_a_v/validator/__init__.py
  miroshnyk_a_v/validator/lib.py
  miroshnyk_a_v/validator/test.py
Labels: shoe

#65 validator
  rudiyov/__init__.py
  rudiyov/dataset_insert_manual.py
  rudiyov/dataset_structure.py
  rudiyov/description.txt
  rudiyov/recursion.py
  rudiyov/validator/__init__.py
  rudiyov/validator/lib.py
  rudiyov/validator/test.py
Labels: shoe

#88 validator
  oliinykao/dataset_insert_manual.py
  oliinykao/dataset_structure.py
  oliinykao/description
  oliinykao/recursion.py
  oliinykao/validator/lib.py
  oliinykao/validator/test.py
Labels: shoe

#87 validator
  romanovmd/__init__.py
  romanovmd/dataset_insert_manual.py
  romanovmd/dataset_structure.py
  romanovmd/description.txt
  romanovmd/integration/__init__.py
  romanovmd/recursion.py
  romanovmd/validator/__init__.py
  romanovmd/validator/lib.py
  romanovmd/validator/test.py
Labels: shoe

#15 dataset_structure
  DrobyazkoOV/__init__.py
  DrobyazkoOV/dataet_insert_manual.py
  DrobyazkoOV/dataset_structure.py
  DrobyazkoOV/description.txt
  DrobyazkoOV/recursion.py
  DrobyazkoOV/validator/__init__.py
  DrobyazkoOV/validator/lib.py
  DrobyazkoOV/validator/test.py
Labels: shoe

#113 validator
  Fedorchenkory/__init__.py
  Fedorchenkory/dataset_insert_manual.py
  Fedorchenkory/dataset_structure.py
  Fedorchenkory/description.txt
  Fedorchenkory/recursion.py
  Fedorchenkory/validator/__init__.py
  Fedorchenkory/validator/lib.py
  Fedorchenkory/validator/test.py
Labels: shoe

#99 validator
  hudymvm/__init__.py
  hudymvm/dataset_insert_manual.py
  hudymvm/dataset_structure.py
  hudymvm/description.txt
  hudymvm/recursion.py
  hudymvm/validator/__init__.py
  hudymvm/validator/lib.py
  hudymvm/validator/test.py
Labels: bug, shoe

#122 validator
  burdenkods/__init__.py
  burdenkods/dataset_structure.py
  burdenkods/description.txt
  burdenkods/recursion.py
  burdenkods/validator/__init__.py
  burdenkods/validator/lib.py
  burdenkods/validator/test.py
Labels: shoe

#11 dataset_structure
  PoliatskaAA/dataset_insert_manual.py
  PoliatskaAA/dataset_structure.py
  PoliatskaAA/description
  PoliatskaAA/recursion.py
  PoliatskaAA/validator/__init__.py
  PoliatskaAA/validator/lib.py
  PoliatskaAA/validator/test.py
  tereshchenkoio/validator/lib.py
Labels: bug, shoe

#25 dataset_structure
  kondrashovavo/dataset_structure.py
  kondrashovavo/description.txt
  kondrashovavo/recursion.py
Labels: medical

#41 dataset_structure
  pyndykivskiytr/dataset_insert_manual.py
  pyndykivskiytr/dataset_structure.py
  pyndykivskiytr/description.txt
  pyndykivskiytr/lib.py
  pyndykivskiytr/recursion.py
  pyndykivskiytr/test.py
  pyndykivskiytr/validator/lib.py
  pyndykivskiytr/validator/test.py
Labels: medical

#101 dataset_structure
  kisivks/__init__.py
  kisivks/dataset_insert_manual.py
  kisivks/dataset_structure.py
  kisivks/description.txt
  kisivks/recursion.py
  kisivks/validator/__init__.py
  kisivks/validator/lib.py
  kisivks/validator/test.py
Labels: medical

#84 dataset_structure
  ZaytsevED/__init__.py
  ZaytsevED/dataset_insert_manual.py
  ZaytsevED/dataset_structure.py
  ZaytsevED/description.txt
  ZaytsevED/recursion.py
  ZaytsevED/validator/__init__.py
  ZaytsevED/validator/lib.py
  ZaytsevED/validator/test.py
Labels: medical

#107 dataset_structure
  bondarilya/dataset_insert_manual.py
  bondarilya/dataset_structure.py
  bondarilya/description.txt
  bondarilya/recursion.py
  bondarilya/validator/__init__.py
  bondarilya/validator/lib.py
  bondarilya/validator/test.py
Labels: medical

#108 validator
  BorysenkoBR/dataset_insert_manual.py
  BorysenkoBR/dataset_structure.py
  BorysenkoBR/description.txt
  BorysenkoBR/recursion.py
  BorysenkoBR/test.py
  BorysenkoBR/validator/lib.py
Labels: medical

#109 validator
  chernyshaa/datasert_insert_manual.py
  chernyshaa/recursion.py
  chernyshaa/validator/lib.py
  chernyshaa/validator/test.py
Labels: medical

#119 validator
  PankeyevaSD/__init__.py
  PankeyevaSD/dataset_insert_manual.py
  PankeyevaSD/dataset_structure.py
  PankeyevaSD/description.txt
  PankeyevaSD/recursion.py
  PankeyevaSD/validator/__init__.py
  PankeyevaSD/validator/lib.py
  PankeyevaSD/validator/test.py
Labels: medical

#132 validator
  egorkravchenko/dataset_insert_manual.py
  egorkravchenko/dataset_structure.py
  egorkravchenko/description.txt
  egorkravchenko/lib.py
  egorkravchenko/test.py
Labels: medical

#37 dataset_structure
  MashyrAM/__init__.py
  MashyrAM/dataset_structure.py
  MashyrAM/description.txt
  MashyrAM/recursion.py
  MashyrAM/validator/__init__.py
  MashyrAM/validator/dataset_insert_manual.py
  MashyrAM/validator/lib.py
  MashyrAM/validator/test.py
Labels: medical

#71 dataset_structure
  KornienkoT/_init__.py
  KornienkoT/dataset_insert_manual.py
  KornienkoT/dataset_structure.py
  KornienkoT/description.txt
  KornienkoT/recursion.py
  KornienkoT/validator/lib.py
  KornienkoT/validator/test.py
Labels: airbnb

#74 dataset_structure
  Lanovenko/dataset_insert_manual.py
  Lanovenko/dataset_structure.py
  Lanovenko/description.txt
  Lanovenko/recursion.py
  Lanovenko/validator/lib.py
  Lanovenko/validator/test.py
Labels: airbnb

#77 dataset_structure
  ChukhBV/dataset_insert_manual.py
  ChukhBV/dataset_structure.py
  ChukhBV/description.txt
  ChukhBV/recursion.py
  ChukhBV/test.py
  ChukhBV/validator/lib.py
Labels: airbnb

#79 dataset_structure
  BelovodskiyIA/__init__.py
  BelovodskiyIA/dataset_insert_manual.py
  BelovodskiyIA/dataset_structure.py
  BelovodskiyIA/description.txt
  BelovodskiyIA/recursion.py
  BelovodskiyIA/validator/__init__.py
  BelovodskiyIA/validator/lib.py
  BelovodskiyIA/validator/test.py
Labels: airbnb

#80 dataset_structure
  amelin/dataset_insert_manual.py
  amelin/dataset_structure.py
  amelin/description.txt
  amelin/recursion.py
  amelin/validator/lib.py
  amelin/validator/test.py
Labels: airbnb

#104 dataset_structure
  shchehelskyiho/__init__.py
  shchehelskyiho/dataset_insert_manual.py
  shchehelskyiho/dataset_structure.py
  shchehelskyiho/description.txt
  shchehelskyiho/recursion.py
  shchehelskyiho/validator/__init__.py
  shchehelskyiho/validator/lib.py
  shchehelskyiho/validator/test.py
Labels: airbnb

#123 recursion
  DahnovskaUO/dataset_insert_manual.py
  DahnovskaUO/dataset_structure.py
  DahnovskaUO/description.txt
  DahnovskaUO/recursion.py
  DahnovskaUO/validator/lib.py
  DahnovskaUO/validator/test.py
Labels: airbnb

#131 dataset_structure
  torbaso/dataset_insert_manual.py
  torbaso/dataset_structure.py
  torbaso/description.txt
  torbaso/recursion.py
  torbaso/validator/lib.py
  torbaso/validator/test.py
Labels: airbnb

#133 validator and data insert manual added
  validator/lib.py
  validator/test.py
  yarovoyde/dataset_insert_manual.py
  yarovoyde/recursion.py
  yarovoyde/validator/lib.py
  yarovoyde/validator/test.py
Labels: airbnb

#136 validator
  Rodina/dataset_insert_manual.py
  Rodina/dataset_structure.py
  Rodina/description.txt
  Rodina/recursion.py
  Rodina/validator/lab.py
  Rodina/validator/test.py
Labels: airbnb

#151 recurtion.validator
  lashtabegav/dataset_insert_manual.py
  lashtabegav/dataset_structure.py
  lashtabegav/description.txt
  lashtabegav/recursion.py
  lashtabegav/validator/lib.py
  lashtabegav/validator/test.py
Labels: airbnb

#154 dataset_structure
  bespalovad/dataset_insert_manual.py
  bespalovad/dataset_structure.py
  bespalovad/description.txt
  bespalovad/recursion.py
  bespalovad/validator/lib.py
  bespalovad/validator/test.py
Labels: airbnb

#114 validator
  .gitignore
  nadya/__init__.py
  nadya/dataset_insert_manual.py
  nadya/dataset_structure.py
  nadya/description.txt
  nadya/recursion.py
  nadya/validator/__init__.py
  nadya/validator/lib.py
  nadya/validator/test.py
Labels: bug, shoe

#115 validators
  IghnatenkoMO/__init__.py
  IghnatenkoMO/dataset_insert_manual.py
  IghnatenkoMO/dataset_structure.py
  IghnatenkoMO/description.txt
  IghnatenkoMO/validator/lib.py
  IghnatenkoMO/validator/test.py
Labels: bug, shoe

#121 dataset_structure
  Bonduryansky_K_U/__init__.py
  Bonduryansky_K_U/dataset_structure.py
  Bonduryansky_K_U/description.txt
Labels: nyc

#126 dataset_common_insert
  rudiyov/integration/__init__.py
  rudiyov/integration/dataset_common_insert.py
  rudiyov/integration/dataset_structure_common.py
  rudiyov/recursion.py
Labels: shoe

#127 dataset_common_insert
  Fedorchenkory/validator/lib.py
  stefanyshynni/intergration/__init__.py
  stefanyshynni/intergration/dataset_common_insert.py
  stefanyshynni/intergration/dataset_structure_common.py
Labels: shoe

#128 dataset_common_insert
  dorotiuktimdt/dataset_insert_manual.py
  dorotiuktimdt/dataset_structure.py
  dorotiuktimdt/integration/__init__.py
  dorotiuktimdt/integration/dataset_common_insert.py
  dorotiuktimdt/integration/dataset_structure_common.py
Labels: shoe

#150 dataset_common_insert
  Fedorchenkory/Integration/__init__.py
  Fedorchenkory/Integration/dataset_common_insert.py
  Fedorchenkory/Integration/dataset_structure_common.py
Labels: shoe

#145 dataset_common_insert
  miroshnyk_a_v/integration/__init__.py
  miroshnyk_a_v/integration/dataset_common_insert.py
  miroshnyk_a_v/integration/dataset_structure_common.py
Labels: shoe

#139 dataset_common_insert
  hudymvm/integration/TitomyrOY_validator_lib.py
  hudymvm/integration/__init__.py
  hudymvm/integration/dataset_common_insert.py
  hudymvm/integration/dataset_structure_common.py
Labels: shoe

#142 dataset_structure_common
  DrobyazkoOV/dataet_insert_manual.py
  DrobyazkoOV/dataset_structure.py
  DrobyazkoOV/description.txt
  DrobyazkoOV/intergration/__init__.py
  DrobyazkoOV/intergration/dataset_common_insert.py
  DrobyazkoOV/intergration/dataset_structure_common.py
  DrobyazkoOV/recursion.py
  DrobyazkoOV/validator/lib.py
  DrobyazkoOV/validator/test.py
Labels: shoe

#138 dataset_structure_common
  NedilkoDV/integration/__init__.py
  NedilkoDV/integration/ann_valid.py
  NedilkoDV/integration/dataset_common_insert.py
  NedilkoDV/integration/dataset_structure_common.py
  NedilkoDV/validator/lib.py
Labels: shoe

#135 dataset_structure_common
  TitimyrOY/dataset_insert_manual.py
  TitimyrOY/recursion.py
  TitomyrOY/integration/__init__.py
  TitomyrOY/integration/dataset_common_insert.py
  TitomyrOY/integration/dataset_structure_common.py
Labels: shoe

#42 dataset_strucutre
  maliarenkoma/__init__.py
  maliarenkoma/dataset_inset_manual.py
  maliarenkoma/dataset_structure.py
  maliarenkoma/description.txt
  maliarenkoma/recursion.py
  maliarenkoma/validator/__init__.py
  maliarenkoma/validator/lib.py
  maliarenkoma/validator/test.py
  pobiedimskasi/dataset_structure.py
  pobiedimskasi/description.txt
  pobiedimskasi/recursion.py
Labels: nyc

#44 validator
  StarenchenkoNV/__init__.py
  StarenchenkoNV/dataset_insert_manual.py
  StarenchenkoNV/dataset_structure.py
  StarenchenkoNV/description.txt
  StarenchenkoNV/recursion.py
  StarenchenkoNV/validator/__init__.py
  StarenchenkoNV/validator/lib.py
  StarenchenkoNV/validator/test.py
Labels: nyc

#50 dataset_structure
  SydorovaOS/__init__.py
  SydorovaOS/dataset_insert_manual.py
  SydorovaOS/dataset_structure.py
  SydorovaOS/description.txt
  SydorovaOS/recursion.py
  SydorovaOS/validator/__init__.py
  SydorovaOS/validator/lib.py
  SydorovaOS/validator/test.py
Labels: nyc

#51 dataset_structure
  usatovsv/__init__.py
  usatovsv/dataset_insert_manual.py
  usatovsv/dataset_structure.py
  usatovsv/description.txt
  usatovsv/recursion.py
  usatovsv/validator/__init__.py
  usatovsv/validator/lib.py
  usatovsv/validator/test.py
Labels: nyc

#52 dataset_structure
  LutakMV/__init__.py
  LutakMV/dataset_insert_manual.py
  LutakMV/dataset_structure.py
  LutakMV/discription.txt
  LutakMV/recursion.py
  LutakMV/validator/__init__.py
  LutakMV/validator/lib.py
  LutakMV/validator/test.py
Labels: nyc

#53 dataset_structure
  Ivanova_es/__init__.py
  Ivanova_es/dataset_insert_manual.py
  Ivanova_es/dataset_structure.py
  Ivanova_es/description.txt
  Ivanova_es/recursion.py
  Ivanova_es/validator/__init__.py
  Ivanova_es/validator/lib.py
  Ivanova_es/validator/test.py
Labels: nyc

#55 dataset_structure
  Maistruk/__init__.py
  Maistruk/dataset_insert_manual.py
  Maistruk/dataset_structure.py
  Maistruk/description.txt
  Maistruk/recursion.py
  Maistruk/validator/__init__.py
  Maistruk/validator/lib.py
  Maistruk/validator/test.py
Labels: nyc

#59 dataset_structure
  sydorovos/__init__.py
  sydorovos/dataset_insert_manual.py
  sydorovos/dataset_structure.py
  sydorovos/description.txt
  sydorovos/recursion.py
  sydorovos/validator/__init__.py
  sydorovos/validator/lib.py
  sydorovos/validator/test.py
Labels: nyc

#67 dataset_structure
  tsakhloev/__init__.py
  tsakhloev/dataset_insert_manual.py
  tsakhloev/dataset_structure.py
  tsakhloev/description.txt
  tsakhloev/recursion.py
  tsakhloev/validator/__init__.py
  tsakhloev/validator/lib.py
  tsakhloev/validator/test.py
Labels: airbnb

#70 dataset_structure
  DanilovID/__init__.py
  DanilovID/dataset_insert_manual.py
  DanilovID/dataset_structure.py
  DanilovID/description.txt
  DanilovID/recursion.py
  DanilovID/validator/__init__.py
  DanilovID/validator/lib.py
  DanilovID/validator/test.py
Labels: airbnb

#72 dataset_structure
  VolosheniukY/dataset_insert_manual.py
  VolosheniukY/dataset_structure.py
  VolosheniukY/description.txt
  VolosheniukY/recursion.py
  VolosheniukY/validator/lib.py
  VolosheniukY/validator/test.py
Labels: airbnb

#73 dataset_structure
  SaltykovAn/__init__.py
  SaltykovAn/dataset_insert_manual.py
  SaltykovAn/dataset_structure.py
  SaltykovAn/description.txt
  SaltykovAn/recursion.py
  SaltykovAn/validator/__init__.py
  SaltykovAn/validator/lib.py
  SaltykovAn/validator/test.py
Labels: airbnb

#129 dataset_structure
  Sazonenko/dataset_insert_manual.py
  Sazonenko/dataset_structure.py
  Sazonenko/description.txt
  Sazonenko/recursion.py
Labels: nyc

#117 recursion
  GermanchukAV/dataset_insert_manual.py
  GermanchukAV/dataset_structure.py
  GermanchukAV/description.txt
  GermanchukAV/recursion.py
  GermanchukAV/validator/lib.py
  GermanchukAV/validator/test.py
Labels: airbnb, bug, reviewed

#156 dataset_structure_common
  torbaso/integration/dataset_common_insert.py
  torbaso/integration/dataset_structure_common.py
  torbaso/validator/lib.py
  torbaso/validator/test.py
Labels: airbnb

#158 recursion&integration update
  dovgaleo/integration/dataset_common_insert.py
  dovgaleo/recursion.py
Labels: bug, medical, reviewed

#28 validator(fixed 2.0)
  shcherbachenkoma/dataset_insert_manual.py
  shcherbachenkoma/dataset_structure.py
  shcherbachenkoma/description.txt
  shcherbachenkoma/recursion.py
  shcherbachenkoma/validator/lib.py
  shcherbachenkoma/validator/test.py
Labels: bug, medical, reviewed

#160 daraset_common_insert
  PankeyevaSD/validator/lib.py
  pavlovskaki/integration/__init__.py
  pavlovskaki/integration/dataset_common_insert.py
  pavlovskaki/integration/dataset_structure_common.py
Labels: airbnb

#159 dataset_structure_common
  danylevichoo/dataset_insert_manual.py
  danylevichoo/dataset_structure.py
  danylevichoo/description.txt
  danylevichoo/integration/dataset_common_insert.py
  danylevichoo/integration/dataset_structure_common.py
  danylevichoo/integration/description.txt
  danylevichoo/recursion.py
  danylevichoo/test.py
  danylevichoo/validator/lib.py
Labels: airbnb

#161 dataset_structure
  pyndykivskiytr/dataset_insert_manual.py
  pyndykivskiytr/lib.py
  pyndykivskiytr/test.py
  pyndykivskiytr/validator/__init__.py
  pyndykivskiytr/validator/lib.py
Labels: medical, reviewed

#43 dataset_structure
  KoretsOleksandr/dataset_insert_manual.py
  KoretsOleksandr/dataset_structure.py
  KoretsOleksandr/description.txt
  KoretsOleksandr/recursion.py
  KoretsOleksandr/validator/__init__.py
  KoretsOleksandr/validator/lib.py
  KoretsOleksandr/validator/test.py
Labels: bug, nyc, reviewed

#56 dataset_strucure
  RyzhkovaDO/dataset_insert_manual.py
  RyzhkovaDO/dataset_structure.py
  RyzhkovaDO/description.txt
  RyzhkovaDO/validator/lib.py
  RyzhkovaDO/validator/test.py
Labels: bug, nyc, reviewed

#47 dataset_structure
  PindaMV/__init__.py
  PindaMV/dataset_insert_manual.py
  PindaMV/dataset_structure.py
  PindaMV/description.txt
  PindaMV/recursion.py
  PindaMV/validator/__init__.py
  PindaMV/validator/lib.py
  PindaMV/validator/test.py
Labels: bug, nyc, reviewed

#58 dataset_structure
  TernytskaNO/__init__.py
  TernytskaNO/dataset_insert_manual.py
  TernytskaNO/dataset_structure.py
  TernytskaNO/description.txt.txt
  TernytskaNO/recursion.py
  TernytskaNO/validator/__init__.py
  TernytskaNO/validator/lib.py
  TernytskaNO/validator/test.py
Labels: bug, nyc, reviewed

#61 dataset_structure
  danylenkoka/__init__.py
  danylenkoka/dataset_insert_manual.py
  danylenkoka/dataset_structure.py
  danylenkoka/description.txt
  danylenkoka/recursion.py
  danylenkoka/validator/__init__.py
  danylenkoka/validator/lib.py
  danylenkoka/validator/test.py
Labels: bug, nyc, reviewed

#62 dataset_structure
  MykhailenkoYE/changed_dataset_structure.py
  MykhailenkoYE/dataset_insert_manual.py
  MykhailenkoYE/description.txt
  MykhailenkoYE/validator/lib.py
  MykhailenkoYE/validator/test.py
Labels: bug, nyc, reviewed

#63 dataset_structure
  Matvienko/__init__.py
  Matvienko/dataset_insert_manual.py
  Matvienko/dataset_structure.py
  Matvienko/description.txt
  Matvienko/recursion.py
  Matvienko/validator/__init__.py
  Matvienko/validator/lib.py
  Matvienko/validator/test.py
Labels: bug, nyc, reviewed

#78 dataset_structure
  MalininR.P/__init__.py
  MalininR.P/description.txt
  MalininR.P/lib.py
  MalininR.P/task2.py
  MalininR.P/task3.py
  MalininR.P/task4.py
  MalininR.P/test.py
  malininrp/dataset_insert_manual.py
  malininrp/dataset_structure.py
  malininrp/description.txt
  malininrp/integration/dataset_common_insert.py
  malininrp/integration/dataset_structure_common.py
  malininrp/recursion.py
  malininrp/validator/__init__.py
  malininrp/validator/lib.py
  malininrp/validator/test.py
Labels: airbnb, bug, reviewed

#148 dataset_structure, validator
  holenyshchenkosd/dataset_insert_manual.py
  holenyshchenkosd/dataset_structure.py
  holenyshchenkosd/description.txt
  holenyshchenkosd/integration/dataset_structure_common.py
  holenyshchenkosd/integration/validator.py
  holenyshchenkosd/recursion.py
  holenyshchenkosd/validator/lib.py
  holenyshchenkosd/validator/test.py
Labels: bug, medical, not fixed, reviewed

#186 dataset_structure_common, dataset_common_insert
  lashtabegav/dataset_insert_manual.py
  lashtabegav/integration/dataset_common_insert.py
  lashtabegav/integration/dataset_structure_common.py
  lashtabegav/integration/description.txt
  lashtabegav/validator/lib.py
Labels: airbnb

#192 recursion
  egorkravchenko/recursion
Labels: medical, reviewed

#200 dataset_structure_common
  ZaytsevED/dataset_insert_manual.py
  ZaytsevED/integration/__init__.py
  ZaytsevED/integration/dataset_structure_common.py
  ZaytsevED/recursion.py
Labels: medical, reviewed

#207 Перероблена робота. Файла для інтеграції не знайдено.
  popovskiiAL/__init__.py
  popovskiiAL/dataset_insert_manual.py
  popovskiiAL/dataset_structure.py
  popovskiiAL/delete this.py
  popovskiiAL/description.txt
  popovskiiAL/validator/__init__.py
  popovskiiAL/validator/lib.py
  popovskiiAL/validator/test.py
Labels: nyc

#205 dataset_common_insert
  TernytskaNO/description.txt
  TernytskaNO/description.txt.txt
  TernytskaNO/integratoin/__init__.py
  TernytskaNO/integratoin/dataset_common_insert.py
  TernytskaNO/integratoin/dataset_stucture_common.py
  TernytskaNO/integratoin/description.txt
  TernytskaNO/validator/lib.py
Labels: nyc

#204 dataset_common_insert
  Ivanova_es/dataset_structure.py
  maistrukia/__init__.py
  maistrukia/dataset_insert_manual.py
  maistrukia/dataset_structure.py
  maistrukia/description.txt
  maistrukia/integration/__init__.py
  maistrukia/integration/dataset_common_insert.py
  maistrukia/integration/dataset_structure_common.py
  maistrukia/recursion.py
  maistrukia/validator/__init__.py
  maistrukia/validator/lib.py
  maistrukia/validator/test.py
Labels: nyc

#203 dataset_common_insert
  Bonduryansky_K_U/dataset_structure.py
  StarenchenkoNV/integration/__init__.py
  StarenchenkoNV/integration/dataset_common_insert.py
  StarenchenkoNV/integration/dataset_structure_common.py
  StarenchenkoNV/validator/lib.py
Labels: nyc

#201 dataset_common_insert
  LutakMV/integration/__init__.py
  LutakMV/integration/dataset_common_insert.py
  LutakMV/integration/dataset_structure_common.py
Labels: nyc

#198 Dataset structure common, dataset common insert
  RyzhkovaDO/integration/dataset_common_insert.py
  RyzhkovaDO/integration/validator_lib_NoskovIlyas.py
  RyzhkovaDO/integration/​dataset_structure_common.py
Labels: nyc

#197 dataset_structure_common
  PindaMV/integration/__init__.py
  PindaMV/integration/dataset_common_insert.py
  PindaMV/integration/dataset_structure_common.py
  PindaMV/integration/validator_lib_andrey.py
Labels: nyc

#196 dataset_structure_common
  SydorovaOS/integration/__init__.py
  SydorovaOS/integration/dataset_common_insert.py
  SydorovaOS/integration/dataset_structure_common.py
Labels: nyc

#187 dataset_common_insert
  MykhailenkoYE/integration/dataset_common_insert.py
  MykhailenkoYE/integration/dataset_structure_common.py
Labels: nyc

#188 dataset_structure_common
  Matvienko/integration/__init__.py
  Matvienko/integration/dataset_common_insert.py
  Matvienko/integration/dataset_structure_common.py
  Matvienko/validator/test.py
Labels: nyc

#191 dataset_structure_common
  Sazonenko/__init__.py
  Sazonenko/dataset_insert_manual.py
  Sazonenko/dataset_structure.py
  Sazonenko/integration/__init__.py
  Sazonenko/integration/dataset_common_insert.py
  Sazonenko/integration/dataset_structure_common.py
  Sazonenko/validator/__init__.py
  Sazonenko/validator/lib.py
  Sazonenko/validator/test_lib.py
  maliarenkoma/dataset_structure.py
Labels: nyc

#46 dataset_structure,dataset_stucture_common, dataset_common_insert
  MalakhatkaOV/__init__.py
  MalakhatkaOV/dataset_insert_manual.py
  MalakhatkaOV/dataset_structure.py
  MalakhatkaOV/description
  MalakhatkaOV/integration/__init__.py
  MalakhatkaOV/integration/dataset_insert_common.py
  MalakhatkaOV/integration/dataset_structure_common.py
  MalakhatkaOV/recursion.py
  MalakhatkaOV/validator/__init__.py
  MalakhatkaOV/validator/lib.py
  MalakhatkaOV/validator/test.py
Labels: bug, not fixed, nyc, reviewed

#48 dataset_structure
  NoskovIlyas/__init__.py
  NoskovIlyas/data_insert_manual.py
  NoskovIlyas/dataset_structure.py
  NoskovIlyas/description.txt
  NoskovIlyas/recursion.py
  NoskovIlyas/validator/__init__.py
  NoskovIlyas/validator/lib.py
  NoskovIlyas/validator/test.py
Labels: bug, not fixed, nyc, reviewed

#68 validator
  zernovmo/dataset_insert_manual.py
  zernovmo/dataset_structure.py
  zernovmo/description.txt
  zernovmo/recursion.py
  zernovmo/task1.py
  zernovmo/validator/__init__.py
  zernovmo/validator/lib.py
  zernovmo/validator/test.py
Labels: airbnb, bug, not fixed, reviewed

#102 dataset_structure
  Костюк Владислава км-93/dataset_insert_manual.py
  Костюк Владислава км-93/description.txt
  Костюк Владислава км-93/pul request dataset_structure.py
  Костюк Владислава км-93/recursion.py
  Костюк Владислава км-93/test.py
Labels: bug, medical, not fixed, reviewed

#103 recursion
  StrelsovIM/dataset_structure.py.py
  StrelsovIM/descriprion.txt.txt
  StrelsovIM/integration/dataset_common_insert.py
  StrelsovIM/integration/dataset_structure_common.py
  StrelsovIM/recursion.py
  StrelsovIM/validator/lib.py
  StrelsovIM/validator/test.py
  StrelsovIllia/dataset_structure.py
  StrelsovIllia/description.txt.txt
  dataset_insert_manual.py
  recursion.py
Labels: bug, medical, not fixed, reviewed

#110 dataset_structure
  khomyakiv/dataset_structure.py
  khomyakiv/description.txt
Labels: bug, medical, not fixed, reviewed

#143 dataset_stucture_common, dataset_common_insert
  burdenkods/validator/lib.py
  romanovmd/dataset_insert_manual.py
  romanovmd/integration/dataset_common_insert.py
  romanovmd/integration/dataset_structure_common.py
Labels: bug, not fixed, reviewed, shoe

#193 task 6
  egorkravchenko/dataset_structure_common.py
Labels: bug, medical, reviewed

#141 dataset_structure
  stefanyukva/__init__.py
  stefanyukva/dataset_insert_manual.py
  stefanyukva/dataset_structure.py
  stefanyukva/description
  stefanyukva/validator/__init__.py
  stefanyukva/validator/lib.py
  stefanyukva/validator/test.py
Labels: bug, not fixed, nyc, reviewed
